### Variables
@authToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImIwYWFkZjY5LTExYjctNDVlZS1hMDJjLWU5ZDIxMTgwNzhjOSIsImlhdCI6MTcwMjE0ODg2OCwiZXhwIjoxNzAyMjM1MjY4fQ.2JfJvIcTaXcSWNVlXdtfV6nof7vf3G2HqVLNl0wbk9c
@uuid=34d1a403-051d-4078-a92f-7e0c37cde6cc
@uuid_task=2aff0e3c-37ec-43f0-8dbe-7b2f8c7c0054
@uuid_employee=1704a043-3773-4332-b8b5-0c389733e908
@uuid_team=cfeb434d-9ede-4f9b-91d1-f7bed149e800



### USERS
### GET
GET http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer {{authToken}}
### SEARCH
GET http://localhost:3000/users?page=1&perPage=5
Content-Type: application/json
Authorization: Bearer {{authToken}}

### LOGIN
POST  http://localhost:3000/users/login
content-type: application/json

{
    "email": "admin@d.com",
    "password": "12345"
}
### CREATE

POST http://localhost:3000/users
content-type: application/json

{
    "name": "admin",
    "email": "admin@d.com",
    "password": "12345"
}

### TOWERS

### CREATE
POST http://localhost:3000/tower
content-type: application/json

{
  "code": 1,
  "tower": "0/2",
  "type": "AT",
  "coordinates": { "latitude": "00002", "longitude": "000023" },
  "distance": 200,
  "height": 30,
  "weight": 1000,
  "type_of_foundation_A": "T",
  "type_of_foundation_B": "T",
  "type_of_foundation_C": "T",
  "type_of_foundation_D": "T",
  "type_of_foundation_MC": "T",
  "embargo": "RELEASE"
}

### GET
GET http://localhost:3000/tower/{{uuid}}
Content-Type: application/json

### SEARCH
GET http://localhost:3000/tower?page=1&perPage=5
Content-Type: application/json

### UPDATE
PUT http://localhost:3000/tower/{{uuid}}
content-type: application/json

{
  "code": 2,
  "tower": "100/2",
  "type": "AT",
  "coordinates": { "latitude": "00002", "longitude": "000023" },
  "distance": 200,
  "height": 30,
  "weight": 1000,
  "type_of_foundation_A": "T",
  "type_of_foundation_B": "T",
  "type_of_foundation_C": "T",
  "type_of_foundation_D": "T",
  "type_of_foundation_MC": "T",
  "embargo": "RELEASE"
}


### TASK

### CREATE
POST http://localhost:3000/task
content-type: application/json

{
  "code": 2,
  "stage": "CIVIL",
  "group": "TOPOGRAFIA",
  "name": "Conferencia de Perfil",
  "unit": "km"
}

### GET
GET http://localhost:3000/task/{{uuid_task}}
Content-Type: application/json

### SEARCH
GET http://localhost:3000/task?page=1&perPage=5
Content-Type: application/json

### UPDATE
PUT http://localhost:3000/task/{{uuid_task}}
content-type: application/json

{
  "code": 3,
  "stage": "LANCAMENTO",
  "group": "TOPOGRAFIA",
  "name": "Locação de cavas",
  "unit": "km"
}


### EMPLOYEE

### CREATE
POST http://localhost:3000/employee
content-type: application/json

{
  "registration": "REG-222",
  "fullName": "Mauro Doido Kubs",
  "occupation": "Montador",
  "leadership": true,
  "status": "ACTIVE"
}

### GET
GET http://localhost:3000/employee/{{uuid_employee}}
Content-Type: application/json

### SEARCH
GET http://localhost:3000/employee?page=1&perPage=5
Content-Type: application/json

### UPDATE
PUT http://localhost:3000/employee/{{uuid_employee}}
content-type: application/json

{
  "registration": "REG-002",
  "fullName": "Wellison Branco Rufino",
  "occupation": "Orelha",
  "leadership": true,
  "status": "ACTIVE"
}

### TEAM

### CREATE
POST http://localhost:3000/team
content-type: application/json

{
  "name": "Equip-101",
  "employees": [],
  "equipments": []
}

### GET
GET http://localhost:3000/team/{{uuid_team}}
Content-Type: application/json

### SEARCH
GET http://localhost:3000/team?page=1&perPage=5
Content-Type: application/json

### UPDATE
PUT http://localhost:3000/team/{{uuid_team}}
content-type: application/json

{
  "name": "Equip-200",
  "employees": [],
  "equipments": []
}

### ADD EMPLOYEE
PUT http://localhost:3000/team/add-employee/1704a043-3773-4332-b8b5-0c389733e908
content-type: application/json

{
  "id": "cfeb434d-9ede-4f9b-91d1-f7bed149e800",
  "name": "Equip-005",
  "employees": [],
  "equipments": []
}

### REMOVE EMPLOYEE
PUT http://localhost:3000/team/del-employee/1704a043-3773-4332-b8b5-0c389733e908
content-type: application/json

{
  "id": "cfeb434d-9ede-4f9b-91d1-f7bed149e800",
  "name": "Equip-002",
  "employees": [],
  "equipments": []
}

### PRODUCTION

### CREATE
POST http://localhost:3000/production
content-type: application/json

{
  "status": "EXECUTED",
  "comments": "comentarios...",
  "teams": [],
  "towers": [],
  "taskId": "7718d2e5-c0e0-449d-b888-07ac34d873dc"
}

### GET
GET http://localhost:3000/production/{{uuid_team}}
Content-Type: application/json

### SEARCH
GET http://localhost:3000/production?page=1&perPage=5
Content-Type: application/json
