### Variables
@authToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjU3MWM0MzQ4LWVmNTQtNGE5Ny05M2I1LTdjZWU5Yzc1OGM5NiIsImlhdCI6MTcwNTY2ODU0NCwiZXhwIjoxNzA1NzU0OTQ0fQ.mX5j5AXvkWZNAM5XRAv0lqNcWrdw5JW6qnY1PXTxzmE
@uuid_tower=62924e14-c25b-4339-acfe-5f0b53d9359a
@uuid_task=2aff0e3c-37ec-43f0-8dbe-7b2f8c7c0054
@uuid_employee=c9a952cc-5d5a-4940-b56c-8c3d8a997622
@uuid_team=cfeb434d-9ede-4f9b-91d1-f7bed149e800
@uuid_foundation=e91955be-681f-4bda-9a7c-467ab9f61924
### USERS

### CREATE
POST http://localhost:3000/users
content-type: application/json

{
    "name": "admin",
    "email": "admin@d.com",
    "password": "12345"
}

### LOGIN
POST  http://localhost:3000/users/login
content-type: application/json

{
    "email": "admin@d.com",
    "password": "12345"
}

### GET
GET http://localhost:3000/users
Content-Type: application/json
Authorization: Bearer {{authToken}}

### SEARCH
GET http://localhost:3000/users?page=1&perPage=5
Content-Type: application/json
Authorization: Bearer {{authToken}}

### FOUNDATIONS

### CREATE
POST http://localhost:3000/foundation
content-type: application/json

{
  "project": "AT-FUN-MCA-0001",
  "revision": "0A",
  "description": "AT-TCB-AFL-0.5",
  "excavation_volume": 20,
  "concrete_volume": 15,
  "backfill_volume": 18,
  "steel_volume": 1000
}

### GET
GET http://localhost:3000/foundation/{{uuid_foundation}}
Content-Type: application/json

### SEARCH
GET http://localhost:3000/foundation?page=1&perPage=5
Content-Type: application/json

### UPDATE
PUT http://localhost:3000/foundation/{{uuid_foundation}}
content-type: application/json

{
   "project": "AT-FUN-MCA-0002",
  "revision": "01",
  "description": "AT-TCB-AFL-0.8",
  "excavation_volume": 40,
  "concrete_volume": 20,
  "backfill_volume": 22,
  "steel_volume": 1020
}

### TOWERS

### CREATE
POST http://localhost:3000/tower
content-type: application/json

{
  "code": 1,
  "tower": "0/2",
  "type": "AT",
  "coordinates": { "latitude": "00002", "longitude": "000023" },
  "distance": 200,
  "height": 30,
  "weight": 1000,
  "embargo": "RELEASE",
  "foundations": ["e91955be-681f-4bda-9a7c-467ab9f61924"]
}

### GET
GET http://localhost:3000/tower/{{uuid_tower}}
Content-Type: application/json

### SEARCH
GET http://localhost:3000/tower?page=1&perPage=5
Content-Type: application/json

### UPDATE
PUT http://localhost:3000/tower/{{uuid_tower}}
content-type: application/json

{
  "code": 2,
  "tower": "100/2",
  "type": "AT",
  "coordinates": { "latitude": "00002", "longitude": "000023" },
  "distance": 200,
  "height": 30,
  "weight": 1000,
  "type_of_foundation_A": "T",
  "type_of_foundation_B": "T",
  "type_of_foundation_C": "T",
  "type_of_foundation_D": "T",
  "type_of_foundation_MC": "T",
  "embargo": "RELEASE"
}


### TASK

### CREATE
POST http://localhost:3000/task
content-type: application/json

{
  "code": 2,
  "stage": "CIVIL",
  "group": "TOPOGRAFIA",
  "name": "Conferencia de Perfil",
  "unit": "km"
}

### GET
GET http://localhost:3000/task/{{uuid_task}}
Content-Type: application/json

### SEARCH
GET http://localhost:3000/task?page=1&perPage=5
Content-Type: application/json

### UPDATE
PUT http://localhost:3000/task/{{uuid_task}}
content-type: application/json

{
  "code": 3,
  "stage": "LANCAMENTO",
  "group": "TOPOGRAFIA",
  "name": "Locação de cavas",
  "unit": "km"
}


### EMPLOYEE

### CREATE
POST http://localhost:3000/employee
content-type: application/json

{
  "registration": "REG-222",
  "fullName": "Mauro Doido Kubs",
  "occupation": "Montador",
  "leadership": true,
  "status": "ACTIVE"
}

### GET
GET http://localhost:3000/employee/{{uuid_employee}}
Content-Type: application/json

### SEARCH
GET http://localhost:3000/employee?page=1&perPage=5
Content-Type: application/json

### UPDATE
PUT http://localhost:3000/employee/{{uuid_employee}}
content-type: application/json

{
  "registration": "REG-002",
  "fullName": "Wellison Branco Rufino",
  "occupation": "Orelha",
  "leadership": true,
  "status": "ACTIVE"
}

### TEAM

### CREATE
POST http://localhost:3000/team
content-type: application/json

{
  "name": "Equip-101",
  "employees": [],
  "equipments": []
}

### GET
GET http://localhost:3000/team/{{uuid_team}}
Content-Type: application/json

### SEARCH
GET http://localhost:3000/team?page=1&perPage=5
Content-Type: application/json

### UPDATE
PUT http://localhost:3000/team/{{uuid_team}}
content-type: application/json

{
  "name": "Equip-200",
  "employees": [],
  "equipments": []
}

### ADD EMPLOYEE
PUT http://localhost:3000/team/add-employee/{{uuid_employee}}
content-type: application/json

{
  "id": "8015a036-0a8a-4179-b8f2-6af4d0b956a4",
  "name": "Equip-005",
  "employees": [],
  "equipments": []
}

### REMOVE EMPLOYEE
PUT http://localhost:3000/team/del-employee/{{uuid_employee}}
content-type: application/json

{
  "id": "cfeb434d-9ede-4f9b-91d1-f7bed149e800",
  "name": "Equip-002",
  "employees": [],
  "equipments": []
}

### PRODUCTION

### CREATE
POST http://localhost:3000/production
content-type: application/json

{
  "status": "EXECUTED",
  "comments": "comentarios...",
  "teams": [],
  "towers": [],
  "taskId": "7718d2e5-c0e0-449d-b888-07ac34d873dc"
}

### GET
GET http://localhost:3000/production/{{uuid_team}}
Content-Type: application/json

### SEARCH
GET http://localhost:3000/production?page=1&perPage=5
Content-Type: application/json
