/*
  Warnings:

  - The values [EXECUTADO,PROGRAMADO,ANDAMENTO] on the enum `STATUS_PRODUCTION` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "STATUS_PRODUCTION_new" AS ENUM ('EXECUTED', 'PROGRAMMED', 'PROGRESS');
ALTER TABLE "productions" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "productions" ALTER COLUMN "status" TYPE "STATUS_PRODUCTION_new" USING ("status"::text::"STATUS_PRODUCTION_new");
ALTER TYPE "STATUS_PRODUCTION" RENAME TO "STATUS_PRODUCTION_old";
ALTER TYPE "STATUS_PRODUCTION_new" RENAME TO "STATUS_PRODUCTION";
DROP TYPE "STATUS_PRODUCTION_old";
ALTER TABLE "productions" ALTER COLUMN "status" SET DEFAULT 'EXECUTED';
COMMIT;

-- AlterTable
ALTER TABLE "productions" ALTER COLUMN "status" SET DEFAULT 'EXECUTED',
ALTER COLUMN "startTime" DROP NOT NULL,
ALTER COLUMN "finalTime" DROP NOT NULL;
